### ISSUE TITLE
Interop with Javascript

### ISSUE THREAD

**Issue by jonathanbp** [zlanguage/zcomp#11]
Is it possible to import a zlang module in a Javascript project?

**Comment by N8python** [comment]
Yes, this would work fine. Z is designed to have plenty of interop with JavaScript, Z functions are JS functions, Z numbers are JavaScript numbers, etc. The interop is not perfect (custom operators in Z are clunky to use in JS). However, if you define a module in Z, transpile it to JS, and `require` the resulting JavaScript file, everything should work fine.
For example, if I created a file named `hello.zlang`:
```
export func () { log("Hello World") }
```
Then, I transpiled it with:
```sh
zcomp transpile hello.zlang
```
Then, I create a "helloFromZ.js" file, and I require the `hello.js` file generated by the Z Compiler:
```js
const hello = require("hello.js") // This imports the transpiled "hello world" function
hello() // Logs "Hello World"
```
Because of this interop, Z programs can also use any npm package.

**Comment by jonathanbp** [comment]
Nice!

It gave me an error though:

```
internal/modules/cjs/loader.js:589
    throw err;
    ^

Error: Cannot find module '@zlanguage/zstdlib'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
    at Function.Module._load (internal/modules/cjs/loader.js:513:25)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/jonathan/Development/github.com/jonathanbp/zhello/hello.js:3:12)
```

I had done `npm link zstdlib` as per the `README.md` but I believe that should be `npm link @zlanguage/zstdlib` instead? That fixes it for me anyway.

Very cool language btw - I'm a fan of both Coffeescript and Elm and this seems like a good mix.

**Comment by N8python** [comment]
Thx! Ill update the docs with npm link @zlanguage/zstdlib
