### ISSUE TITLE
Request to rename Z programming language to Slava Ukraine

### ISSUE THREAD

**Issue by sntp** [zlanguage/zcomp#616]
Dear zlang community,

I would like to request a rename of the Z programming language to "Slava Ukraine" in support of Ukraine amidst the current conflict with Russia.

As many of you may know, Z is the Russian symbol of war, and given the recent events in Ukraine, it seems inappropriate to continue using a language with such a name.

By renaming the language to "Slava Ukraine," we can show our support for Ukraine and its people during these difficult times. Additionally, this would be a small but meaningful gesture to demonstrate solidarity with those who are affected by the ongoing conflict.

I understand that renaming a programming language is a significant undertaking, but I believe that it would be a worthy effort to make a difference. I would like to request that the zlang community support this initiative and work towards implementing the change.

Thank you for considering this request.

**Comment by N8python** [comment]
Oh no. This is such an old project of mine... I wasn't keeping track of it and didn't make this connection. Renaming the entire language is quite the undertaking, especially because it's no longer actively maintained. Perhaps a disclaimer would do just service - or including a Ukrainian flag in the README?
